/**
 * HARDWARE DOG / THE INCIDENT LIBRARY (LVL 95)
 *
 * Not a social network: a repository of anonymized, reproducible cases.
 *
 *   cases/<category>/HD-C042.hdlog       the recording (anonymized if real)
 *   cases/<category>/HD-C042.case.json   what replaying it must produce,
 *                                        and the incident in words
 *
 * A submission is a pull request with those two files. The rules below
 * run on every pull request (hwdog test cases); a reviewer then reads the
 * words and the console lines. docs/LIBRARY.md.
 */

import type { CaseFile } from './cases';
import { caseFrom, replayRecording } from './cases';
import type { DiagnosisId } from './diagnostics';
import { anonymize, findLeaks, type AnonymizeSummary } from './anonymize';
import { parseHdlog } from './session';

export const CATEGORIES = ['baseline', 'power', 'usb', 'uart', 'network', 'i2c'] as const;
export type Category = (typeof CATEGORIES)[number];

export const CATEGORY_TITLE: Record<Category, string> = {
  baseline: 'healthy sessions: what normal looks like',
  power: 'supply, cable, current: the rail',
  usb: 'the USB link of the target',
  uart: 'the serial console: baud, resets',
  network: 'link, DHCP, gateway, DNS, upstream',
  i2c: 'the I2C bus and its devices',
};

/** Where an incident belongs: the domain of its first diagnosis (the cause comes first). */
const DOMAIN: Record<DiagnosisId, Category> = {
  POWER_INSTABILITY: 'power',
  SUPPLY_SAG: 'power',
  OVERCURRENT: 'power',
  USB_INTERMITTENT: 'usb',
  USB_NOT_ENUMERATED: 'usb',
  TARGET_RESET_LOOP: 'uart',
  SERIAL_CONFIGURATION_MISMATCH: 'uart',
  NO_LINK: 'network',
  DHCP_FAILURE: 'network',
  GATEWAY_UNREACHABLE: 'network',
  DNS_FAILURE: 'network',
  UPSTREAM_FAILURE: 'network',
  NETWORK_UNSTABLE: 'network',
  NETWORK_POWER_LOSS: 'network',
  I2C_DEVICE_DISAPPEARED: 'i2c',
  I2C_BUS_INSTABILITY: 'i2c',
};

export const categoryOf = (diagnoses: readonly { id: DiagnosisId }[]): Category => (diagnoses[0] ? DOMAIN[diagnoses[0].id] : 'baseline');

/** A recording for the library stays small enough to review and to clone. */
export const MAX_CASE_BYTES = 8 * 1024 * 1024;

/** Words a template leaves for the contributor to replace. */
const PLACEHOLDER = /\bTODO\b|\.\.\.\s*$/;

/**
 * What keeps a case out of the library (empty: it may go in). The replay
 * check (checkCase) is separate: this is about the file being fit to
 * share and to understand.
 */
export function libraryProblems(c: CaseFile, hdlog: string, dir: string): string[] {
  const out: string[] = [];
  if (!(CATEGORIES as readonly string[]).includes(dir)) out.push(`directory "${dir}" is not a category (${CATEGORIES.join(', ')})`);
  if (c.category !== dir) out.push(`category "${c.category ?? '(none)'}" but the case sits in ${dir}/`);
  if (!/^HD-C\d{3,}$/.test(c.id)) out.push(`id "${c.id}": HD-C followed by a number (HD-C042)`);
  if (c.recording.file !== `${c.id}.hdlog`) out.push(`the recording must be named ${c.id}.hdlog`);
  if (!c.title || c.title.length > 120) out.push('a title of 1 to 120 characters');
  else if (PLACEHOLDER.test(c.title)) out.push('the title still holds the template text');
  const ctx = c.context;
  for (const k of ['description', 'hardware', 'expected'] as const) {
    const v = ctx?.[k];
    if (!v || !v.trim()) out.push(`context.${k} is missing: ${CONTEXT_HELP[k]}`);
    else if (PLACEHOLDER.test(v)) out.push(`context.${k} still holds the template text`);
  }
  const bytes = new TextEncoder().encode(hdlog).length;
  if (bytes > MAX_CASE_BYTES) out.push(`recording is ${(bytes / 1048576).toFixed(1)} MiB, the library takes ${MAX_CASE_BYTES / 1048576} MiB at most: cut it around the incident`);
  for (const leak of findLeaks(hdlog)) out.push(`privacy: ${leak}`);
  return out;
}

export const CONTEXT_HELP = {
  description: 'what went wrong, as you saw it',
  hardware: 'board, target, supply, cable, network, firmware: what a reader needs to reproduce it',
  expected: 'what the hardware should have done',
} as const;

/** The library's table of contents, generated: cases/INDEX.md. */
export function libraryIndex(cases: readonly CaseFile[]): string {
  const lines = [
    '# INCIDENT LIBRARY',
    '',
    'Generated by `hwdog index ../cases --write` from the case files: do not edit by hand.',
    'How to add an incident: [`docs/LIBRARY.md`](../docs/LIBRARY.md).',
    '',
  ];
  for (const cat of CATEGORIES) {
    const here = cases.filter((c) => c.category === cat).sort((a, b) => a.id.localeCompare(b.id));
    lines.push(`## ${cat.toUpperCase()}`, '', CATEGORY_TITLE[cat], '');
    if (here.length === 0) {
      lines.push('No case yet.', '');
      continue;
    }
    lines.push('| CASE | ORIGIN | INCIDENT | DIAGNOSIS |', '|---|---|---|---|');
    for (const c of here) {
      const diag = c.expect.diagnoses.map((d) => `${d.id} ${d.confidence}`).join(', ') || 'none';
      lines.push(`| [${c.id}](${cat}/${c.id}.case.json) | ${c.recording.origin} | ${c.title.replace(/\|/g, '/')} | ${diag} |`);
    }
    lines.push('');
  }
  const physical = cases.filter((c) => c.recording.origin === 'PHYSICAL').length;
  lines.push(`${cases.length} case(s), ${physical} recorded on real hardware.`, '');
  return lines.join('\n');
}

/**
 * A recording ready to submit: anonymized, its case drafted on the right
 * shelf, the words left for the contributor (TODO: the library refuses
 * the case until they are written). The copy must replay to the same
 * diagnosis as the original, or nothing is produced.
 */
export async function prepareForLibrary(original: string): Promise<{ case: CaseFile; hdlog: string; summary: AnonymizeSummary; file: string }> {
  const before = await replayRecording(parseHdlog(original));
  const { hdlog, summary } = anonymize(original);
  const recording = parseHdlog(hdlog);
  const after = await replayRecording(recording);
  const say = (d: typeof before.diagnoses) => JSON.stringify(d.map((x) => [x.id, x.confidence, x.evidence]));
  if (say(before.diagnoses) !== say(after.diagnoses)) throw new Error('the anonymized copy does not replay to the same diagnosis: nothing saved (please report this recording)');
  const id = `HD-C-${recording.header.recording.slice(0, 8)}`;
  const first = after.diagnoses[0];
  const c = caseFrom(after, recording, {
    id,
    title: `${first ? first.title : 'No finding'}: TODO short title`,
    file: `${id}.hdlog`,
    category: categoryOf(after.diagnoses),
    context: {
      description: `TODO: ${CONTEXT_HELP.description}`,
      hardware: `TODO: ${CONTEXT_HELP.hardware}`,
      expected: `TODO: ${CONTEXT_HELP.expected}`,
    },
  });
  return { case: c, hdlog, summary, file: id };
}
